# =============================================================================
# nginx.conf - Configuración del servidor web Nginx (variante A)
# =============================================================================
# - Sirve por HTTPS (443) con el certificado autofirmado.
# - Exige autenticación básica (htpasswd).
# =============================================================================

server {
    listen 443 ssl;
    server_name _;

    # Certificado x.509 autofirmado generado en el Dockerfile.
    # Ruta dentro del contenedor donde está el certificado público
    ssl_certificate     /etc/nginx/certs/server.crt; 
    # Ruta hacia la clave privada
    ssl_certificate_key /etc/nginx/certs/server.key; 


    # Define el directorio raíz del contenedor donde residen los archivos web
    root  /usr/share/nginx/html;
    # Establece el archivo HTML principal que se cargará por defecto
    index index.html;

    # Aplica las siguientes reglas de seguridad a toda la web
    location / {
        # Activa la ventana emergente de login con este mensaje informativo
        auth_basic "Area restringida - Caso Practico 2 UNIR";
        
        # Indica la ruta del archivo con los usuarios y contraseñas cifrados
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        # Busca el archivo solicitado y, si no existe, devuelve un error 404
        try_files $uri $uri/ =404;
    }
}
